// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptio'
              'ns have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Q9mM-uwvSFdbSGxF7S993glgsG_LT7I',
    appId: '1:402153985860:ios:60d2de08038a5b2f216911',
    messagingSenderId: '402153985860',
    projectId: 'checkinchuckles',
    storageBucket: 'checkinchuckles.appspot.com',
    iosBundleId: 'com.example.checkinchuckles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Q9mM-uwvSFdbSGxF7S993glgsG_LT7I',
    appId: '1:402153985860:ios:60d2de08038a5b2f216911',
    messagingSenderId: '402153985860',
    projectId: 'checkinchuckles',
    storageBucket: 'checkinchuckles.appspot.com',
    iosBundleId: 'com.example.checkinchuckles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnBotGPAQrnz85r5aNRpHv6HaMkjGL6ys',
    appId: '1:402153985860:web:6754462a1877f1f3216911',
    messagingSenderId: '402153985860',
    projectId: 'checkinchuckles',
    authDomain: 'checkinchuckles.firebaseapp.com',
    storageBucket: 'checkinchuckles.appspot.com',
    measurementId: 'G-P64RFHJEV9',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnBotGPAQrnz85r5aNRpHv6HaMkjGL6ys',
    appId: '1:402153985860:web:1bdbdd00d140c887216911',
    messagingSenderId: '402153985860',
    projectId: 'checkinchuckles',
    authDomain: 'checkinchuckles.firebaseapp.com',
    storageBucket: 'checkinchuckles.appspot.com',
    measurementId: 'G-M8HZTB8YLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC69ZVgjoAfgbVvpCSjHw_zBp48zH12OUU',
    appId: '1:402153985860:android:64f80596406f8b37216911',
    messagingSenderId: '402153985860',
    projectId: 'checkinchuckles',
    storageBucket: 'checkinchuckles.appspot.com',
  );

}